title: Sravan Anumula
description: My Personal Engineering Wiki

# Use remote theme
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

# Personal site → IMPORTANT
baseurl: ""
url: "https://sanumula.github.io"

# Enable search
search_enabled: true

# Navigation behavior
nav_sort: case_insensitive

# Footer
footer_content: "© Sravan Anumula"

# Optional: back to top
back_to_top: true
back_to_top_text: "Back to top"
