title: Sravan Anumula
description: My Personal Engineering Wiki
theme: just-the-docs

# Personal site → IMPORTANT
baseurl: ""
url: "https://sanumula.github.io"

# Enable search
search_enabled: true

# Navigation behavior
nav_sort: case_insensitive

# Footer
footer_content: "© Sravan Anumula"

# Optional: back to top
back_to_top: true
back_to_top_text: "Back to top"
